---
title: "scrape-orders"
author: "Alex Cookson"
date: "31/10/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries

```{r}
library(tidyverse)
library(lubridate)
```

Set up lists, etc. (url is https://storage.googleapis.com/evekit_md/2019/01/05/trades_allregions_20190105.gz)

```{r}
url_table <- as_tibble(seq(ymd("2010-01-01"), ymd("2020-12-31"), by = "day")) %>%
  rename(date = value) %>%
  mutate(year = format.Date(date, "%Y"),
         month = format.Date(date, "%m"),
         day = format.Date(date, "%d"),
         file_name = str_c("trades_allregions_", year, month, day, ".gz"),
         url = str_c("https://storage.googleapis.com/evekit_md/", year, "/", month, "/", day, "/", file_name))

download_list <- url_table %>%
  filter(between(date, ymd("2019-05-10"), ymd("2019-05-31"))) %>%
  pull(url)

map(download_list, ~ download.file(., destfile = paste0("./data/raw-gz/", basename(.))))
```
☺